browser_deb_pkgs:
    - dbus-x11
    - gdebi
    - google-chrome-stable
    - libcurl3
    - libgconf2-4
    - libnss3-1d
    - libxss1
    - xdg-utils
    - xvfb

# Firefox
browser_custom_deb_pkgs:
    - {
         name: "firefox_42.0+build2-0ubuntu1_amd64.deb",
         url: "http://launchpadlibrarian.net/223743022/firefox_42.0+build2-0ubuntu1_amd64.deb" 
      }

# Chrome and ChromeDriver
chrome_repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
chromedriver_version: 2.25
chromedriver_url: "http://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip"

# PhantomJS
phantomjs_version: "phantomjs-1.9.8-linux-x86_64"
phantomjs_tarfile: "{{ phantomjs_version }}.tar.bz2"
phantomjs_url: "https://bitbucket.org/ariya/phantomjs/downloads/{{ phantomjs_tarfile }}"

browser_xvfb_display: ":1"
